import { Container, Header } from "@/shared/components/shared"
import { Suspense } from "react"

export const metadata = {
    title: 'Pretty Ice Cream | Cart',
    description: 'Generated by Next.js',
  }
  
  export default function CheckoutLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (    
        <main className="min-h-screen bg-[#fcf7fa]">
            <Container>
                <Suspense>
                  <Header hasSearch={false} hasCart={false} className="border-b-gray-200" />
                </Suspense>
                
                {children}
            </Container>          
        </main>
    )
  }